slurm:
  partition: pgi-8-gpu-h100
  cpus-per-task: 8 # How many CPUs to allocate to each of your experiments
  mem: 30G # How much memory to allocate to each of your experiments 
  ntasks-per-node: 1 # How many copies of your experiment to start per node
  gres: gpu:h100:1 # How many GPUs to allocate to each of your experiments 
